server:
  servlet:
    context-path: "/booking"

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
      generate-ddl: true
      show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    deserialization:
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true